Repository near/near-explorer, pull requests merged in 2021-12, with the labels that each got.

#792 refactor: Update packages
  backend/models/index.js
  backend/package-lock.json
  backend/package.json
  backend/src/near.js
  backend/src/wamp.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/api/nodes.js
  package-lock.json
Labels: dependencies, refactoring

#806 feat(backend): Update `seat_price` algorithm
  backend/package-lock.json
  backend/package.json
  backend/src/near.js
  frontend/package-lock.json
  frontend/package.json
Labels: New Feature

#809 refactor: Upgrade Next.js
  frontend/.babelrc
  frontend/jest.config.js
  frontend/next-env.d.ts
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
Labels: dependencies

#811 refactor: Upgrade jest
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#816 refactor(frontend): Next.js-generated jest config
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.js.snap
  frontend/src/components/accounts/__tests__/__snapshots__/AccountRow.test.js.snap
  frontend/src/components/blocks/__tests__/__snapshots__/BlockDetails.test.tsx.snap
  frontend/src/components/blocks/__tests__/__snapshots__/BlocksRow.test.tsx.snap
  frontend/src/components/nodes/__test__/__snapshots__/NodeRow.test.tsx.snap
  frontend/src/components/nodes/__test__/__snapshots__/NodesEpoch.test.tsx.snap
  frontend/src/components/nodes/__test__/__snapshots__/ValidatorRow.test.tsx.snap
  frontend/src/components/nodes/__test__/__snapshots__/ValidatorsList.test.tsx.snap
  frontend/src/components/transactions/ActionIcons.tsx
  frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap
  frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
  frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap
  frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
  frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
  frontend/src/components/utils/__tests__/__snapshots__/AccountLink.test.tsx.snap
  frontend/src/components/utils/__tests__/__snapshots__/CardCell.test.tsx.snap
  frontend/src/components/utils/__tests__/__snapshots__/ReceiptLink.test.tsx.snap
  frontend/src/components/utils/__tests__/__snapshots__/Term.test.tsx.snap
Labels: refactoring

#818 Refactor(frontend): add act fn as per react documentation
  frontend/src/libraries/tester.js
Labels: refactoring

#826 refactor(backend): Refactor logic of validators staking status
  backend/src/near.js
Labels: refactoring

#823 Refactor (frontend): typed jest
  frontend/jest.config.ts
  frontend/jest.setup.js
  frontend/jest.setup.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__mocks__/mixpanel-browser/index.ts
  frontend/src/components/accounts/__tests__/AccountDetails.test.tsx
  frontend/src/components/accounts/__tests__/AccountRow.test.js
  frontend/src/components/accounts/__tests__/AccountRow.test.tsx
  frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.tsx.snap
  frontend/src/components/accounts/__tests__/__snapshots__/AccountRow.test.tsx.snap
  frontend/src/libraries/tester.tsx
Labels: refactoring

#827 Refactor (frontend): Typed Next.js API
  frontend/additional.d.ts
  frontend/src/libraries/explorer-wamp/stats.ts
  frontend/src/pages/api/circulating-supply-in-near.ts
  frontend/src/pages/api/circulating-supply.ts
  frontend/src/pages/api/fees-of-previous-7-days-utc.ts
  frontend/src/pages/api/fees-of-previous-day-utc.ts
  frontend/src/pages/api/metrics/indexer.ts
  frontend/src/pages/api/nodes.ts
  frontend/src/pages/api/status.ts
Labels: refactoring

#825 Refactor (frontend): typed cypress
  frontend/cypress/integration/account-details-navigation.spec.ts
  frontend/cypress/integration/accounts-list-page.spec.ts
  frontend/cypress/integration/blocks-list-page.spec.ts
  frontend/cypress/integration/dashboard-page.spec.ts
  frontend/cypress/integration/dashboard-search.spec.ts
  frontend/cypress/integration/nodes-page.spec.ts
  frontend/cypress/integration/transactions-page.spec.ts
  frontend/cypress/support/index.js
  frontend/cypress/tsconfig.json
  frontend/tsconfig.json
Labels: refactoring

#824 Refactor (frontend): typed Next.js config
  frontend/next.config.js
  frontend/next.config.ts
  frontend/src/__mocks__/next/config.js
  frontend/src/__mocks__/next/config.ts
  frontend/src/components/accounts/AccountDetails.tsx
  frontend/src/context/NetworkProvider.tsx
  frontend/src/libraries/config.ts
  frontend/src/libraries/explorer-wamp/index.ts
Labels: refactoring

#822 Refactor (frontend): typed pages
  frontend/Dockerfile
  frontend/next.config.ts
  frontend/src/components/accounts/AccountDetails.tsx
  frontend/src/components/utils/Content.tsx
  frontend/src/context/DatabaseProvider.tsx
  frontend/src/context/NetworkProvider.tsx
  frontend/src/context/NodeProvider.tsx
  frontend/src/libraries/config.ts
  frontend/src/libraries/consts.js
  frontend/src/libraries/language.ts
  frontend/src/libraries/moment.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/accounts/[id].tsx
  frontend/src/pages/accounts/index.tsx
  frontend/src/pages/blocks/[hash].tsx
  frontend/src/pages/blocks/index.tsx
  frontend/src/pages/contracts/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/nodes/online-nodes.tsx
  frontend/src/pages/nodes/validators.tsx
  frontend/src/pages/partner/index.tsx
  frontend/src/pages/stats/index.tsx
  frontend/src/pages/transactions/[hash].tsx
  frontend/src/pages/transactions/index.tsx
Labels: refactoring

#820 Refactor (frontend): typed-components
  frontend/src/components/nodes/NodesCard.tsx
  frontend/src/components/stats/ProtocolConfigInfo.tsx
  frontend/src/components/transactions/TransactionsFilterByType.jsx
  frontend/src/components/transactions/TransactionsHeader.jsx
  frontend/src/components/utils/Balance.tsx
  frontend/src/components/utils/Footer.tsx
  frontend/src/components/utils/GasPrice.tsx
  frontend/src/components/utils/Header.tsx
  frontend/src/components/utils/HeaderNavDropdown.tsx
  frontend/src/components/utils/HeaderNetworkDropdown.tsx
  frontend/src/components/utils/LocalizeWrapper.tsx
  frontend/src/components/utils/MobileHeaderNavDropdown.tsx
  frontend/src/components/utils/PaginationSpinner.tsx
  frontend/src/components/utils/Search.tsx
  frontend/src/components/utils/StorageSize.tsx
  frontend/src/components/utils/Timer.tsx
Labels: refactoring

#828 Refactor (frontend): remove excessive comments
  frontend/src/pages/accounts/[id].tsx
  frontend/src/pages/blocks/[hash].tsx
  frontend/src/pages/transactions/[hash].tsx
Labels: refactoring

#837 Refactor (frontend): no absolute imports
  frontend/src/hooks/use-near-network.ts
  frontend/src/pages/accounts/[id].tsx
  frontend/src/pages/stats/index.tsx
Labels: refactoring

#838 Refactor (frontend): mixpanel as hook
  frontend/src/components/utils/Footer.tsx
  frontend/src/components/utils/HeaderNetworkDropdown.tsx
  frontend/src/components/utils/Link.tsx
  frontend/src/components/utils/Search.tsx
  frontend/src/components/utils/Term.tsx
  frontend/src/components/utils/WalletLink.tsx
  frontend/src/hooks/analytics/use-analytics-init.ts
  frontend/src/hooks/analytics/use-analytics-track-on-mount.ts
  frontend/src/hooks/analytics/use-analytics-track.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/accounts/[id].tsx
  frontend/src/pages/accounts/index.tsx
  frontend/src/pages/blocks/[hash].tsx
  frontend/src/pages/blocks/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/nodes/online-nodes.tsx
  frontend/src/pages/nodes/validators.tsx
  frontend/src/pages/partner/index.tsx
  frontend/src/pages/stats/index.tsx
  frontend/src/pages/transactions/[hash].tsx
  frontend/src/pages/transactions/index.tsx
Labels: refactoring

#836 Refactor (frontend): server-side props
  frontend/cypress/integration/account-details-navigation.spec.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/accounts/[id].tsx
  frontend/src/pages/blocks/[hash].tsx
  frontend/src/pages/transactions/[hash].tsx
Labels: refactoring

#835 Refactor (frontend): Network context
  frontend/src/components/accounts/AccountDetails.tsx
  frontend/src/components/accounts/__tests__/AccountDetails.test.tsx
  frontend/src/components/utils/HeaderNetworkDropdown.tsx
  frontend/src/context/NetworkContext.tsx
  frontend/src/context/NetworkProvider.tsx
  frontend/src/hooks/use-near-network.ts
  frontend/src/hooks/use-network-context.ts
  frontend/src/libraries/config.ts
  frontend/src/libraries/explorer-wamp/index.ts
  frontend/src/libraries/tester.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/accounts/[id].tsx
  frontend/src/pages/api/circulating-supply-in-near.ts
  frontend/src/pages/api/circulating-supply.ts
  frontend/src/pages/stats/index.tsx
Labels: refactoring
